function output_handles = v_plotwindow(parent)
initGUI();

handles.model = AnalyzerModel.ModalAnalysisModel();
handles.dataListener = event.listener(handles.model, 'timeDataChanged',...
    @(source,event) onChangedData(handles.fig, handles.data));

guidata(handles.panel_plotwindow, handles);
output_handles = handles.panel_plotwindow;

    function initGUI()
        handles.panel_plotwindow = uipanel('Parent',parent,...
            'Title','Plot Panel',...
            'FontSize',9,...
            'Position',[10 10 0.8 0.9],...
            'Units','pixels',...
            'SizeChangedFcn',@resizepanel,...
            'BorderType','none',...
            'BackgroundColor',[1 1 1]);
        handles.button = uicontrol('Parent',handles.panel_plotwindow,...
            'Style','pushbutton',...
            'String','Mein PlotButton',...
            'Position',[10 10 100 30],...
            'Units','pixels');
    end

    function resizepanel(hObject,event)
        
    end
end

function onChangedData(hObject, data)
end
