function [handles panel_settings] = v_settings(parent)
handles = guidata(parent);
initGUI();
handles.model = AnalyzerModel.ModalAnalysisModel();

guidata(handles.panel_settings, handles);
panel_settings = handles.panel_settings;


    function initGUI()
        handles.panel_settings = uipanel('Parent',parent,...
            'Title','Settings Panel',...
            'FontSize',9,...
            'Position',[10 10 0.8 0.9],...
            'Units','pixels',...
            'SizeChangedFcn',@resizepanel,...
            'BorderType','none',...
            'BackgroundColor',[0.95 0.95 0.95]);
        handles.button = uicontrol('Parent',handles.panel_settings,...
            'Style','pushbutton',...
            'String','Mein SettingsButton',...
            'Position',[10 10 100 30],...
            'Units','pixels');
    end

    function resizepanel(hObject,event)
        
    end
end


